version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - node_modules:/app/node_modules
    depends_on:
      - backend

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  node_modules:
