# Use the official Python image from the Docker Hub
FROM python:3.12

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define environment variable
ENV PYTHONUNBUFFERED=1

# Run both the FastAPI server and the Celery worker
CMD ["sh", "-c", "celery -A tasks.celery_app worker --loglevel=info & uvicorn main:app --host 0.0.0.0 --port 8000"]
